eureka:
  client:
    service-url:
      #注册中心地址
#      defaultZone: http://ha1:8761/eureka/,http://ha2:8771/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
server:
  port: 9002
# service name
spring:
  application:
    name: service-trace2
